name: ci

on:
  push:
  pull_request:

jobs:
  linux-cpu-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Offline Regression Suite
        run: bash ./scripts/run-tests.sh full
